// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AuthProvider } from '../lib/AuthContext';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
         <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
